version: '3.9'

services:

  web:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"  
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=cuestionario
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   depends_on:
  #     - db

volumes:
  pgdata: